[workspace]
authors = ["W.A. Odil Janandith <odiljanandith@gmail.com>"]
channels = ["conda-forge", "robostack-humble"]
name = "DL_project"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
setup = "pip install -e mobileclip"

[dependencies]
python = "3.11.*"
pip = "*"
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-turtlesim = ">=1.4.2,<2"
ros-humble-ament-cmake-auto = ">=1.3.3,<2"
compilers = ">=1.8.0,<2"
pkg-config = ">=0.29.2,<0.30"
cmake = ">=3.27.4,<4"
ninja = ">=1.13.2,<2"

[pypi-dependencies]
open-clip-torch = ">=2.20.0"
timm = ">=0.9.5"
torch = ">=2.1.0"
torchvision = ">=0.16.0"